### ISSUE TITLE
Privacy breach

### ISSUE THREAD

**Issue by cryptarch** [Mitko88/MI-map#1]
Hi,

I'm a University of Melbourne employee. It has come to my attention that the file https://github.com/Mitko88/MI-map/blob/master/IRMS%20DB%20content/IRMS%20DB%20content/outgoingExchange.sql has personal student information in it.

Even if the information is out of date I don't think these students would want information like their weighted grade average, citizenship, travel details, and so forth all kept on the public internet.

I know you probably put it on GitHub by accident. Could you please remove it as soon as possible?

Thanks,

Tim Rice
Research Platform Services

**Comment by Mitko88** [comment]
I deleted the repository. Thank you for this.

**Comment by cryptarch** [comment]
Awesome, thanks very much for your prompt action

**Comment by andrewspiers** [comment]
https://github.com/Mitko88/MI-map/blob/master/IRMS%20DB%20content/IRMS%20DB%20content/outgoingExchange.sql 
file is still visible for me
